fix problem with setting cam_in%cflx for dms in cap
NorESMhub/CAM pull request #174
Opened 2024-10-29 18:35 UTC by mvertens

In atm_import_export.F90, cam_in%cflx(icol,pndx_fdms) is set correctly when dms is obtained from the ocean component.
However, it is reset to 0 in chemistry.F90. So what needs to be done in the short term is to set cam_in%cflx(icol,pndx_fdms) in aero_model.F90 parallel to how it is set when dms is read from a file rather than being obtained from the ocean component.

**NOTE: this must wait for an update to oslo_aero!**

2024-10-29 21:30 UTC, gold2718 requested changes
Please add a comment
Also, Externals_CAM.cfg will need to be updated before this PR is ready.

2024-10-29 21:30 UTC, gold2718 commented on src/cpl/nuopc/atm_import_export.F90
>               cam_in(c)%fdms(i) = -fldptr1d(g) * med2mod_areacor(g)
Please comment this as to why we are using a new field instead of `cflx`.

2024-10-30 20:05 UTC, mvertens commented on src/cpl/nuopc/atm_import_export.F90
>               cam_in(c)%fdms(i) = -fldptr1d(g) * med2mod_areacor(g)
Done.

2024-10-31 09:04 UTC, gold2718 requested changes
This looks good now, just need to change the OSLO_AERO tag to `noresm_oslo_aero_v2`.

2024-10-31 09:14 UTC, mvertens commented
I'm update the OSLO_AERO tag. Is this good to be merged now?

2024-10-31 09:14 UTC, gold2718 approved these changes
Looks good now

2024-10-31 09:17 UTC, merged