noresm2_3_develop : add compset NF1850norbc_tropstratchem_aer2014
NorESMhub/CAM pull request #182
Opened 2024-11-28 20:07 UTC by DirkOlivie

Summary: add compset NF1850norbc_tropstratchem_aer2014 - allows to estimate the anthropogenic aerosol ERF

Contributors: Dirk Olivié (@DirkOlivie)

Reviewers: Steve Goldhaber (@gold2718) and Øyvind Seland (@oyvindseland)

Purpose of changes: include extra compset NF1850norbc_tropstratchem_aer2014 (issue #181)

Github PR URL: 

Changes made to build system: None

Changes made to the namelist: there is a new use_cases file for the new compset (1850_cam6_noresm_tropstratchem_aer2014.xml).

Changes to the defaults for the boundary datasets: None.  But new specific emission files are available for this new compset.  However only emission files for the f19 resolution are available.  For the f09 resolution, the model will not run as I have put in 1850_cam6_noresm_tropstratchem_aer2014.xml:
```xml
<ext_frc_specifier hgrid="0.9x1.25">
  'SPECIES ->  NOTAVAILABLE'
</ext_frc_specifier>
```
and
```xml
<srf_emis_specifier hgrid="0.9x1.25">
  'SPECIES -> NOTAVAILABLE'
</srf_emis_specifier>
```
Is this  a good solution?

Substantial timing or memory changes: None

Detailed description of changes

Issues addressed by this PR: 
#181 (noresm2_3_develop : NF1850norbc_tropstratchem_aer2014 compset)

2024-11-29 08:43 UTC, oyvindseland commented
I imagine there are better methods to inform that a compset does not work for a given resolution?
@gold2718

2024-12-04 21:49 UTC, gold2718 requested changes
The current handling of missing emission files happens at run time. I think it should happen as early as possible. See DirkOlivie/CAM#2.

2025-05-02 09:52 UTC, DirkOlivie commented
Hi Steve, I have now accepted your PR related to better handling of missing emissions files.  Can you review this "updated" PR?  Best regards, Dirk

2025-05-05 19:14 UTC, gold2718 requested changes
I have a few change requests. Please let me know if you think any of them are unwarranted.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--do_beljaars>           .true.   </do_beljaars-->
I suggest either taking out these comments or restoring the settings with the correct values.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!-- No srf_emis_specifier for hgrid="0.9x1.25" -->
Is this because it is missing or because it is not needed?

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--prescribed_strataero_cycle_yr>  1850          </prescribed_strataero_cycle_yr-->
For these, also please remove commented settings or replace with correct settings.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--megan_specifier>'isoprene = isoprene','monoterp = myrcene + sabinene + limonene+ carene_3 + ocimene_t_b + pinene_b + pinene_a'</megan_specifier-->
Please remove this comment.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--monoterp_oslo_emis_file>noresm-only/atm/cam/chem/trop_mozart_aero/emis/soanucl/bvocgcmFV19_monoterp_1850_2000_zero.nc </monoterp_oslo_emis_file-->
Please remove these commented settings.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--rad_climate>'A:Q:H2O','N:O2:O2','A:CO2:CO2','N:ozone:O3','A:N2O:N2O','A:CH4:CH4','N:CFC11STAR:CFC11','A:CFC12:CFC12'</rad_climate-->
Please remove these commented settings.

2025-05-05 19:14 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +       'SAD_ICE','SAD_LNAT','SAD_SULFC','SAD_TROP','SAD_AERO',
I think removing this blank line will help readability.

2025-05-05 19:14 UTC, gold2718 commented on cime_config/config_compsets.xml
> +    <lname>1850_CAM60%NORESM%NORBC%TROPSTRATCHEM%AER2014_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV</lname>
I think a short test for this configuration would be useful. I suggest an `ERP` test.

2025-05-06 08:49 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--do_beljaars>           .true.   </do_beljaars-->
Hi Steve, thanks for your review!  I think it is indeed cleaner to not have these lines.  However, if we remove these lines in 1850_cam6_noresm_tropstratchem_aer2014.xml, we should remove them in all noresm use-cases for visual consistency.  As there are 68 noresm use-cases, it is quite some work.  Do you think we should do it?

2025-05-06 08:53 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!-- No srf_emis_specifier for hgrid="0.9x1.25" -->
Hi Steve, these emissions exist currently for only for 1.9x2.5 and not for 0.9x1.25 horizontal resolution.  We assume that this sensitivity experiment by most people will only be run on 1.9x2.5 horizontal resolution.  We can however generate the 0.9x1.25 emission data on demand.

2025-05-06 08:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--megan_specifier>'isoprene = isoprene','monoterp = myrcene + sabinene + limonene+ carene_3 + ocimene_t_b + pinene_b + pinene_a'</megan_specifier-->
Hi Steve, here I think it makes sense to remove the commented line.  The old  line is how it is done in the aerosol-only version.  Best regards, Dirk

2025-05-06 08:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--prescribed_strataero_cycle_yr>  1850          </prescribed_strataero_cycle_yr-->
Hi Steve, if these lines should be removed, I suggest to remove them in all 68 NorESM use cases.   Best regards, Dirk

2025-05-06 08:57 UTC, DirkOlivie commented on cime_config/config_compsets.xml
> +    <lname>1850_CAM60%NORESM%NORBC%TROPSTRATCHEM%AER2014_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV</lname>
Hi Steve, yes, probably a goo idea.

2025-05-06 08:58 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--rad_climate>'A:Q:H2O','N:O2:O2','A:CO2:CO2','N:ozone:O3','A:N2O:N2O','A:CH4:CH4','N:CFC11STAR:CFC11','A:CFC12:CFC12'</rad_climate-->
Hi Steve, here I think it makes sense to remove the commented line. The old line is how it is done in the aerosol-only version. Best regards, Dirk

2025-05-06 08:59 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +       'SAD_ICE','SAD_LNAT','SAD_SULFC','SAD_TROP','SAD_AERO',
Hi Steve, yes, we can remove it.  Best regards, Dirk

2025-05-06 09:00 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--monoterp_oslo_emis_file>noresm-only/atm/cam/chem/trop_mozart_aero/emis/soanucl/bvocgcmFV19_monoterp_1850_2000_zero.nc </monoterp_oslo_emis_file-->
Hi Steve, yes, good to remove.  However, probably should be done in all 68 NorESM use cases.  Best regards, Dirk

2025-05-06 10:18 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--do_beljaars>           .true.   </do_beljaars-->
I think it is fine to clean as we go. Whenever one of these needs updating or reviewing, we should go over everything and clean any fields that are no longer needed.

2025-05-06 10:19 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!-- No srf_emis_specifier for hgrid="0.9x1.25" -->
In that case, I think the current comment is okay.

2025-05-06 10:22 UTC, gold2718 commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--prescribed_strataero_cycle_yr>  1850          </prescribed_strataero_cycle_yr-->
It is up to you. I can think of a way to quickly remove them from all the files and submit that back to this PR if that helps.

2025-05-06 17:55 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--do_beljaars>           .true.   </do_beljaars-->
I have now cleaned this up in the 5 NorESM tropstrat use_cases : 
- 1850_cam6_noresm_tropstratchem.xml
- 1850_cam6_noresm_tropstratchem_aer2014.xml
- hist_cam6_noresm_tropstratchem.xml
- ssp370_cam6_noresm_tropstratchem.xml
- ssp585_cam6_noresm_tropstratchem.xml

2025-05-06 17:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--prescribed_strataero_cycle_yr>  1850          </prescribed_strataero_cycle_yr-->
I have now cleaned this up in the 5 NorESM tropstrat use_cases : 
- 1850_cam6_noresm_tropstratchem.xml
- 1850_cam6_noresm_tropstratchem_aer2014.xml
- hist_cam6_noresm_tropstratchem.xml
- ssp370_cam6_noresm_tropstratchem.xml
- ssp585_cam6_noresm_tropstratchem.xml

2025-05-06 17:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--megan_specifier>'isoprene = isoprene','monoterp = myrcene + sabinene + limonene+ carene_3 + ocimene_t_b + pinene_b + pinene_a'</megan_specifier-->
I have now cleaned this up in the 5 NorESM tropstrat use_cases : 
- 1850_cam6_noresm_tropstratchem.xml
- 1850_cam6_noresm_tropstratchem_aer2014.xml
- hist_cam6_noresm_tropstratchem.xml
- ssp370_cam6_noresm_tropstratchem.xml
- ssp585_cam6_noresm_tropstratchem.xml

2025-05-06 17:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--monoterp_oslo_emis_file>noresm-only/atm/cam/chem/trop_mozart_aero/emis/soanucl/bvocgcmFV19_monoterp_1850_2000_zero.nc </monoterp_oslo_emis_file-->
I have now cleaned this up in the 5 NorESM tropstrat use_cases : 
- 1850_cam6_noresm_tropstratchem.xml
- 1850_cam6_noresm_tropstratchem_aer2014.xml
- hist_cam6_noresm_tropstratchem.xml
- ssp370_cam6_noresm_tropstratchem.xml
- ssp585_cam6_noresm_tropstratchem.xml

2025-05-06 17:56 UTC, DirkOlivie commented on bld/namelist_files/use_cases/1850_cam6_noresm_tropstratchem_aer2014.xml
> +<!--rad_climate>'A:Q:H2O','N:O2:O2','A:CO2:CO2','N:ozone:O3','A:N2O:N2O','A:CH4:CH4','N:CFC11STAR:CFC11','A:CFC12:CFC12'</rad_climate-->
I have now cleaned this up in the 5 NorESM tropstrat use_cases : 
- 1850_cam6_noresm_tropstratchem.xml
- 1850_cam6_noresm_tropstratchem_aer2014.xml
- hist_cam6_noresm_tropstratchem.xml
- ssp370_cam6_noresm_tropstratchem.xml
- ssp585_cam6_noresm_tropstratchem.xml

2025-05-08 08:47 UTC, gold2718 commented
> I imagine there are better methods to inform that a compset does not work for a given resolution? @gold2718

Should we put a warning  or error into `build-namelist`?

2025-05-12 20:14 UTC, DirkOlivie commented on cime_config/config_compsets.xml
> +    <lname>1850_CAM60%NORESM%NORBC%TROPSTRATCHEM%AER2014_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV</lname>
Hi Steve @gold2718
how should I implement such a test?
Best regards,
Dirk

2025-05-12 20:14 UTC, DirkOlivie commented
Hi Steve @gold2718 
concerning the issue with missing emission files and failing build-namelist : is that possibly already addressed in the PR [2](https://github.com/DirkOlivie/CAM/pull/2), which I accepted?
Best regards, Dirk

2025-05-13 06:54 UTC, gold2718 commented
> Hi Steve @gold2718 concerning the issue with missing emission files and failing build-namelist : is that possibly already addressed in the PR [2](https://github.com/DirkOlivie/CAM/pull/2), which I accepted? Best regards, Dirk

We need to test this to make sure the error message appears. Also, the error message could be made more specific (or just provide some hints as to what the problem might be).

2025-05-27 06:39 UTC, gold2718 commented
@DirkOlivie, the `ERP_Ln9.f09_f09_mtn14.NFHISTnorpddmsbc.betzy_intel.cam-outfrq9s` test has quite a different namelist than the last baseline. Is that expected?

2025-05-27 08:10 UTC, DirkOlivie commented
Hi Steve @gold2718 ,
what are the differences : is it in emission files?  Or something else?

2025-05-27 08:18 UTC, gold2718 commented
> Hi Steve @gold2718 , what are the differences : is it in emission files? Or something else?

It is quite a lot. See:
`diff /cluster/work/users/goldy/camtest/test_aux_cam_noresm_2025_05_25/ERP_Ln9.f09_f09_mtn14.NFHISTnorpddmsbc.betzy_intel.cam-outfrq9s.C.aer2014_fullchem/CaseDocs/atm_in /cluster/shared/noresm/noresm_baselines/cam_develop/noresm2_3_alpha03/ERP_D_Ln9.f19_f19_mtn14.NF1850norbc_tropstratchem.betzy_intel.cam-outfrq9s/CaseDocs/atm_in`

2025-06-04 13:50 UTC, DirkOlivie commented
Hi Steve @gold2718 
concerning the difference between the two atm_in files:
- ERP_Ln9.f09_f09_mtn14.NFHISTnorpddmsbc.betzy_intel.cam-outfrq9s.C.aer2014_fullchem : based on the atm_in, this seems not to be a full-chemistry, but just an aerosol-only simulation.  Is this test done/setup with the correct compset?
- ERP_D_Ln9.f19_f19_mtn14.NF1850norbc_tropstratchem.betzy_intel.cam-outfrq9s : seems to be indeed a full-chemistry compset.

The tests seem to further differ in their horizontal resolution:
- ERP_Ln9.f09_f09_mtn14.NFHISTnorpddmsbc.betzy_intel.cam-outfrq9s.C.aer2014_fullchem : 1x1
- ERP_D_Ln9.f19_f19_mtn14.NF1850norbc_tropstratchem.betzy_intel.cam-outfrq9s : 2x2

Does this help?  Does it make sense?

2025-06-04 21:09 UTC, gold2718 commented
@DirkOlivie, I'm sorry, that difference compared the wrong two tests. Looking at the tropstrat test from the previous baseline, it is only a diagnostic output change.

2025-06-04 21:12 UTC, gold2718 approved these changes
This looks good now, thanks!

2025-06-04 21:15 UTC, merged

2025-06-04 21:19 UTC, gold2718 commented
Tagged as `cam_noresm2_3_v1.0.0f`. Sorry for all the delays.